name: User Service CI

on:
  push:
    branches: [ main ]
    paths:
      - 'services/user-service/**'
      - '.github/workflows/user-service-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/user-service/**'
  workflow_dispatch:

jobs:
  # ================ SECURITY (Secrets) ===================
  gitleaks:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Gitleaks # install gitleaks to scan the code for secrets
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.2_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/
          
      - name: Run Gitleaks (Full History)
        # Standard full history scan
        # exit-code=0 allows pipeline to continue even if leaks are found
        run: gitleaks detect --source=services/user-service --verbose --redact --exit-code=0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

          
      # FUTURE: Uncomment below for incremental scanning(scan only the last commit )
      # - name: Run Gitleaks (Incremental)
      #   run: gitleaks detect --source=services/user-service --log-opts=${{ github.event.before }}..${{ github.sha }} --verbose --redact --exit-code=2

  # ================ TEST ===================
  test:
    name: Test User Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run tests
        working-directory: ./services/user-service
        run: mvn clean test -Dspring.profiles.active=test -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false

  # ================ BUILD ===================
  build:
    name: Build Image
    needs: [test, gitleaks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to tar
        uses: docker/build-push-action@v5
        with:
          context: ./services/user-service
          tags: user-service:${{ github.sha }}
          outputs: type=docker,dest=/tmp/user-service.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: user-service-image
          path: /tmp/user-service.tar 
          retention-days: 1 # keep the artifact for 1 day

  # ================ SCAN ===================
  scan:
    name: Scan Image (Trivy)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: user-service-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/user-service.tar
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'user-service:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  # ================ PUSH ===================
  push:
    name: Push Image
    needs: scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: user-service-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/user-service.tar
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag and Push to DockerHub
        run: |
          docker tag user-service:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/ecopilot-user-service:latest
          docker tag user-service:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/ecopilot-user-service:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ecopilot-user-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ecopilot-user-service:${{ github.sha }}
